# Generated by Django 3.2.7 on 2024-04-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='链接')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='带英文名称')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='city_photo', verbose_name='封面')),
                ('person_count', models.IntegerField(default=0, verbose_name='去过人数')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='英文名称')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='country_photo', verbose_name='封面')),
                ('travel_num', models.IntegerField(default=0, verbose_name='去过人数')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='姓名')),
                ('gender', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('age', models.IntegerField(default=20, verbose_name='年龄')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号码')),
                ('country', models.CharField(default='中国', max_length=64, verbose_name='国籍')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('icon', models.ImageField(blank=True, default='user_icon/default_icon.jpeg', null=True, upload_to='user_icon', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='链接')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='sight_photo', verbose_name='封面')),
                ('grade', models.FloatField(default=0, verbose_name='推荐指数')),
                ('rank', models.TextField(blank=True, null=True, verbose_name='排名')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='提示')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('rate_num', models.IntegerField(default=0, verbose_name='评分人数')),
                ('all_score', models.FloatField(default=0, verbose_name='平均评分')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞人数')),
                ('look_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.city', verbose_name='城市')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
                'db_table': 'sight',
            },
        ),
        migrations.CreateModel(
            name='SearchKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True, verbose_name='搜索关键字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户搜索关键字',
                'verbose_name_plural': '用户搜索关键字',
                'db_table': 'search_key',
            },
        ),
        migrations.CreateModel(
            name='RateSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('sight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_sight', to='travel.sight', verbose_name='景点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评分表',
                'verbose_name_plural': '评分表',
                'db_table': 'rate_sight',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_type', models.CharField(choices=[('0', '文化类'), ('1', '自然类'), ('2', '冒险类'), ('3', '古城类'), ('4', '村落类')], default='0', max_length=20, verbose_name='景点类型')),
                ('cost_min', models.IntegerField(default=1, verbose_name='最低预算')),
                ('cost_max', models.IntegerField(default=10, verbose_name='最高预算')),
                ('travel_way', models.CharField(choices=[('0', '单人行'), ('1', '与家人'), ('2', '与朋友'), ('3', '与搭子')], default='0', max_length=20, verbose_name='出行方式')),
                ('sight_way', models.CharField(choices=[('0', '自驾去'), ('1', '包车去'), ('2', '徒步去'), ('3', '跟团去')], default='0', max_length=20, verbose_name='旅行方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户调查问卷',
                'verbose_name_plural': '用户调查问卷',
                'db_table': 'questionnaire_sight',
            },
        ),
        migrations.CreateModel(
            name='LikeSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('sight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_sight', to='travel.sight', verbose_name='景点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞表',
                'verbose_name_plural': '点赞表',
                'db_table': 'like_sight',
            },
        ),
        migrations.CreateModel(
            name='LikeRecommendSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='是否喜欢')),
                ('reason', models.TextField(blank=True, default=None, null=True, verbose_name='原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.sight', verbose_name='景点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户是否喜欢推荐的景点',
                'verbose_name_plural': '用户是否喜欢推荐的景点',
                'db_table': 'like_recommend_sight',
            },
        ),
        migrations.CreateModel(
            name='CommentSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('like_users', models.TextField(blank=True, default=None, null=True, verbose_name='点赞用户id列表')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('sight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.sight', verbose_name='景点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'comment_sight',
            },
        ),
        migrations.CreateModel(
            name='CollectSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('sight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_sight', to='travel.sight', verbose_name='景点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏表',
                'verbose_name_plural': '收藏表',
                'db_table': 'collect_sight',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.country', verbose_name='国家'),
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='city_photo', verbose_name='图片')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.city', verbose_name='城市')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='BookingSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='预订时间')),
                ('sight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_sight', to='travel.sight', verbose_name='景点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '预订表',
                'verbose_name_plural': '预订表',
                'db_table': 'booking_sight',
            },
        ),
    ]
