# Generated by Django 4.2.27 on 2026-01-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon_feature',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='人脸特征'),
        ),
    ]
