# Generated by Django 4.2.27 on 2026-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_user_icon_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='姓氏'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='名字'),
        ),
    ]
