# Generated by Django 4.2.27 on 2026-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='证件有效期'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='证件号'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('身份证', '身份证'), ('护照', '护照'), ('港澳通行证', '港澳通行证'), ('台胞证', '台胞证'), ('其他', '其他')], max_length=32, null=True, verbose_name='证件类型'),
        ),
    ]
