# Generated by Django 4.2.27 on 2026-02-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_user_id_expiry_date_user_id_number_user_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='链接')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='hotel_photo', verbose_name='封面')),
                ('grade', models.FloatField(default=0, verbose_name='推荐指数')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话')),
                ('price', models.CharField(blank=True, max_length=128, null=True, verbose_name='价格')),
                ('hotel_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='类型')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('rate_num', models.IntegerField(default=0, verbose_name='评分人数')),
                ('all_score', models.FloatField(default=0, verbose_name='平均评分')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞人数')),
                ('look_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.city', verbose_name='城市')),
            ],
            options={
                'verbose_name': '酒店-民宿',
                'verbose_name_plural': '酒店-民宿',
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='RateHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_hotel', to='travel.hotel', verbose_name='酒店')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店评分表',
                'verbose_name_plural': '酒店评分表',
                'db_table': 'rate_hotel',
            },
        ),
        migrations.CreateModel(
            name='LikeHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_hotel', to='travel.hotel', verbose_name='酒店')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店点赞表',
                'verbose_name_plural': '酒店点赞表',
                'db_table': 'like_hotel',
            },
        ),
        migrations.CreateModel(
            name='CommentHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('like_users', models.TextField(blank=True, default=None, null=True, verbose_name='点赞用户id列表')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.hotel', verbose_name='酒店')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店评论表',
                'verbose_name_plural': '酒店评论表',
                'db_table': 'comment_hotel',
            },
        ),
        migrations.CreateModel(
            name='CollectHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_hotel', to='travel.hotel', verbose_name='酒店')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店收藏表',
                'verbose_name_plural': '酒店收藏表',
                'db_table': 'collect_hotel',
            },
        ),
        migrations.CreateModel(
            name='BookingHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='预订时间')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_hotel', to='travel.hotel', verbose_name='酒店')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店预订表',
                'verbose_name_plural': '酒店预订表',
                'db_table': 'booking_hotel',
            },
        ),
    ]
