# Generated by Django 4.2.27 on 2026-02-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_hotel_ratehotel_likehotel_commenthotel_collecthotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='链接')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='shopping_photo', verbose_name='封面')),
                ('grade', models.FloatField(default=0, verbose_name='推荐指数')),
                ('rank', models.TextField(blank=True, null=True, verbose_name='排名')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='提示')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('rate_num', models.IntegerField(default=0, verbose_name='评分人数')),
                ('all_score', models.FloatField(default=0, verbose_name='平均评分')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞人数')),
                ('look_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.city', verbose_name='城市')),
            ],
            options={
                'verbose_name': '购物',
                'verbose_name_plural': '购物',
                'db_table': 'shopping',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='链接')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='food_photo', verbose_name='封面')),
                ('grade', models.FloatField(default=0, verbose_name='推荐指数')),
                ('rank', models.TextField(blank=True, null=True, verbose_name='排名')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='提示')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('rate_num', models.IntegerField(default=0, verbose_name='评分人数')),
                ('all_score', models.FloatField(default=0, verbose_name='平均评分')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞人数')),
                ('look_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.city', verbose_name='城市')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='链接')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='activity_photo', verbose_name='封面')),
                ('grade', models.FloatField(default=0, verbose_name='推荐指数')),
                ('rank', models.TextField(blank=True, null=True, verbose_name='排名')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='提示')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('rate_num', models.IntegerField(default=0, verbose_name='评分人数')),
                ('all_score', models.FloatField(default=0, verbose_name='平均评分')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞人数')),
                ('look_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.city', verbose_name='城市')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity',
            },
        ),
    ]
