# Generated by Django 4.2.27 on 2026-02-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_shopping_food_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='入住日期'),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='退房日期'),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='guest_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='入住人姓名'),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
